### ISSUE TITLE
Reload dev server on file edits

### ISSUE THREAD

**Issue by YahyaFazlani** [Tech-With-Tim/API#31]
**Is your feature request related to a problem? Please describe.**

I have to restart the app every time I make a change which is very time consuming. Doing this with hypercorn's default `config.use_reloader` and watchdog don't work that is why I added this here so if someone would know how to do this.

**Describe the solution you'd like**

The app should reload when I make a change in any of the directories. Similar to what happens in Django, Flask and the default way to run quart. 

**Describe alternatives you've considered**

Using quarts default runner using `app.run` or adding the `QUART_APP` and other quart variable to the .env variables.

**Additional context**

I know this will take time to implement as the above solutions may give errors too.

**Comment by SylteA** [comment]
I've never been able to get this feature to work personally, seeing as you couldnt get it to work either I doubt it does.

As you can see [here](https://github.com/pgjones/quart/blob/ac50cc4d7e743db3b9579d9f4f4d5280b5d0353d/src/quart/app.py#L1723-L1733),
`Quart.run()` also uses hypercorns autoreloader so your alternative solution will not work either.
