### ISSUE TITLE
User username and discrim are unique

### ISSUE THREAD

**Issue by takos22** [Tech-With-Tim/API#38]
## Describe the bug
The User model username and discrim are unique but they shouldn't be. So, `takos#0001` and `takos#6969` would conflict and even worse, `Biz#6969` and `takos#6969` would also conflict.

## To Reproduce
Create 2 users with the same username or discrim.

## Expected behavior
One of the users isn't created because it conflicts with the other user.

## Additional context
None

**Comment by SylteA** [comment]
This should be fixed by making username and discrim PKEYs then ID as Unique.
